// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "e15a996d-fc90-4df3-a3c4-cbe744ec9541");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1622703454);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1594038750);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1594038747);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.defaultLocation", "unfiled");
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1922);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1594038744);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 109);
user_pref("browser.newtabpage.activity-stream.impressionId", "{74e116ee-1f33-40f9-bf6c-193b7328e181}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"idsInUrlbarPreProton\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1594038748580");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1594042348580");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1594038747");
user_pref("browser.slowStartup.averageTime", 3870);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "file:///usr/share/doc/ioi/index.html");
user_pref("browser.startup.homepage_override.buildID", "20210527174632");
user_pref("browser.startup.homepage_override.mstone", "89.0");
user_pref("browser.startup.lastColdStartupCheck", 1622703426);
user_pref("browser.startup.upgradeDialog.version", 89);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"save-to-pocket-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.resultBuckets", "{\"children\":[{\"maxResultCount\":1,\"children\":[{\"group\":\"heuristicTest\"},{\"group\":\"heuristicExtension\"},{\"group\":\"heuristicSearchTip\"},{\"group\":\"heuristicOmnibox\"},{\"group\":\"heuristicUnifiedComplete\"},{\"group\":\"heuristicAutofill\"},{\"group\":\"heuristicTokenAliasEngine\"},{\"group\":\"heuristicFallback\"}]},{\"group\":\"extension\",\"maxResultCount\":5},{\"flexChildren\":true,\"children\":[{\"flexChildren\":true,\"children\":[{\"flex\":2,\"group\":\"formHistory\"},{\"flex\":4,\"group\":\"remoteSuggestion\"},{\"flex\":0,\"group\":\"tailSuggestion\"}],\"flex\":2},{\"group\":\"general\",\"flex\":1}]}]}");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1594038747827");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "89.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "a2c2a436fabc42d8b40f707f4cfc1a49");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210527174632");
user_pref("extensions.lastAppVersion", "89.0");
user_pref("extensions.lastPlatformVersion", "89.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3647872f-1e31-4a8b-a270-ff8403420d8f\",\"formautofill@mozilla.org\":\"ef3e896e-0bbe-42dc-ab90-0335e07b3bac\",\"screenshots@mozilla.org\":\"5f3e9b6f-6e22-491c-bce8-ab8985618cc7\",\"webcompat-reporter@mozilla.org\":\"dd008810-6bf5-4264-b242-a8c8b08a1426\",\"webcompat@mozilla.org\":\"63653d76-0262-4bf9-ad01-c887d46187fd\",\"default-theme@mozilla.org\":\"79ba8f26-13cc-43da-8e06-7f26b24a2676\",\"google@search.mozilla.org\":\"bdfbe82f-1bc4-44ca-b71b-e184dcdee21c\",\"amazondotcom@search.mozilla.org\":\"74b1058f-4f3b-457f-a2df-e288fcf92f40\",\"bing@search.mozilla.org\":\"0358ed0d-579d-4ca1-a769-2a64b2c96d76\",\"ddg@search.mozilla.org\":\"4295fb11-1a3c-4a9e-812a-ecafe093ebe2\",\"ebay@search.mozilla.org\":\"a94585a3-9712-4402-a2e3-71842c75cbcd\",\"wikipedia@search.mozilla.org\":\"cc56eca8-a88d-4165-92dc-92e7c1937f62\",\"pictureinpicture@mozilla.org\":\"2d30081c-14b8-4287-8d86-42ae33de6163\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1622703427);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("general.smoothScroll.mouseWheel.migrationPercent", 0);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20210527174632");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "23ca0d27-5224-410d-b304-a710c35ab362");
user_pref("security.sandbox.plugin.tempDirSuffix", "bfd83a53-8f41-4c81-83df-701db556b495");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1622703420);
user_pref("toolkit.telemetry.cachedClientID", "00755db3-92c2-4c27-821b-8d9b6cb0f68a");
user_pref("toolkit.telemetry.previousBuildID", "20210527174632");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
